apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: google-samples-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: google-samples-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
        